# Generated by Django 5.0.7 on 2024-07-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='client',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
