# Generated by Django 5.0.7 on 2024-07-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_remove_client_user_client_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client',
            new_name='full_name',
        ),
    ]
