# Generated by Django 5.0.7 on 2024-07-12 14:30

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_client_city_alter_client_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default='client.png', upload_to=userauths.models.user_directory_path),
        ),
    ]
