# Generated by Django 5.0.7 on 2024-07-12 14:37

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='images/client.png', upload_to=userauths.models.user_directory_path),
        ),
    ]
