# Generated by Django 5.0.7 on 2024-07-12 15:21

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_alter_client_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='store_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.AddField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(default='client.png', upload_to=userauths.models.user_directory_path),
        ),
    ]
