# Generated by Django 5.0.7 on 2024-07-17 09:42

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='ven', unique=True),
        ),
    ]
