# Generated by Django 5.0.7 on 2024-07-17 09:48

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0012_client_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='vid',
        ),
        migrations.AddField(
            model_name='client',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cli', unique=True),
        ),
    ]
