# Generated by Django 5.0.7 on 2024-07-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_client_alter_billitem_client'),
        ('userauths', '0014_rename_cid_client_lid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
