# Generated by Django 5.0.7 on 2024-07-17 10:08

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_vendor_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='ven', unique=True),
        ),
    ]
