# Generated by Django 5.0.7 on 2024-07-17 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_billitem_amount_billitem_description_billitem_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='client',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='store_name',
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('bill_items', models.ManyToManyField(to='core.billitem')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create-bill', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'create-bill',
            },
        ),
    ]
