# Generated by Django 5.0.7 on 2024-07-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlists',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartOrderItems',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='Wishlists',
        ),
    ]
