# Generated by Django 5.0.7 on 2024-07-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_cartorder_user_remove_cartorderitems_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Clients'},
        ),
    ]
