# Generated by Django 5.0.7 on 2026-01-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_bill_options_alter_tags_options_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gpt_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
