# Generated by Django 5.0.7 on 2026-01-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_client_gpt_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='gpt_enabled',
            new_name='gpt5_enabled',
        ),
    ]
