# Generated by Django 5.0.9 on 2026-01-29 12:36

import core.models
import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Product'},
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='bill_store_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='bill_client_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_user_gpt5_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_featured_status_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to=core.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Product Title', max_length=255),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', '-date'], name='core_produc_user_id_468e66_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', '-date'], name='core_produc_status_6f056e_idx'),
        ),
    ]
